---
abstract: 'Manage posters to a Twitter stream'
author:
  - 'Pedro Figueiredo <me@pedrofigueiredo.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter-Cabal
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::XMPP: 0.3
  Class::Accessor::Fast: 0
  Config::Any: 0
  Log::Log4perl: 0
  MIME::Base64: 0
  Net::Twitter: 2.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
